name: CI Shellcheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Shellcheck
        # not needed in gh actions, but when running locally via act
        run: sudo apt update && sudo apt install shellcheck

      - name: Run shellcheck of *.sh in root directory
        run: shellcheck ui-install.sh

      - name: Run shellcheck in ./general directory
        run: shellcheck general/*.sh

      - name: Run shellcheck in ./distro_installers directory
        run: shellcheck distro_installers/*.sh

      - name: Run shellcheck in ./game-helpers directory
        run: shellcheck game-helpers/*/*.sh
