name: CI Shellcheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Shellcheck
        run: sudo apt update && sudo apt install shellcheck

      - name: Run shellcheck of ui-install.sh
        # SC2086 = ignore globbing check
        run: shellcheck -e SC2086 ui-install.sh

      - name: Run shellcheck of ge-proton.sh
        run: shellcheck ge-proton.sh

      - name: Run shellcheck in ./general directory
        run: shellcheck general/*.sh

      - name: Run shellcheck in ./distro_installers directory
        # SC2086 = ignore globbing check
        # SC1091 = ignore check for source /etc/os-release
        run: shellcheck -e SC2086,SC1091 distro_installers/*.sh

      - name: Run shellcheck in ./.build-helpers directory
        run: shellcheck .build-helpers/*.sh
