---
name: CI Shellcheck

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

  workflow_dispatch:  # manual workflow run from Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Shellcheck
        run: sudo apt update && sudo apt install shellcheck  # needed for act

      - name: Run shellcheck of *.sh in root directory
        run: shellcheck ui-install.sh

      - name: Run shellcheck in ./general directory
        run: shellcheck general/*.sh

      - name: Run shellcheck in ./distro_installers directory
        run: shellcheck distro_installers/*.sh

      - name: Run shellcheck in ./game-helpers directory
        run: shellcheck game-helpers/*/*.sh
